# Generated by Django 3.2.5 on 2021-10-11 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0003_auto_20211011_1821'),
        ('FacilitiesWelfare', '0034_alter_registerorganizationalhouse_isverify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('ConsumerType', models.CharField(choices=[('CA', 'کمک معیشتی'), ('CI', 'اقلام مصرفی'), ('FH', 'کمک بلاعوض')], max_length=2, verbose_name='نوع')),
                ('TypeAssistance', models.CharField(choices=[('PU', 'همگانی'), ('PR', 'خاص'), ('N', 'بدون انتخاب')], default='N', max_length=2, verbose_name='نوع کمک')),
                ('ConsumerTypeItems', models.CharField(choices=[('Fr', 'رایگان'), ('Ca', 'نقدی'), ('N', 'بدون انتخاب')], default='N', max_length=2, verbose_name='آیتم')),
                ('FreeHelp', models.CharField(choices=[('Ma', 'ازدواج'), ('BG', 'هدیه تولد'), ('NC', 'فرزند جدید'), ('N', 'بدون انتخاب')], default='N', max_length=2, verbose_name='نوع هدیه')),
                ('Title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('Description', models.TextField(verbose_name='توضیحات')),
                ('DateRegister', models.DateTimeField(verbose_name='تاریخ ثبت')),
                ('DateExpire', models.DateTimeField(verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'کمک',
                'verbose_name_plural': 'کمک ها',
            },
        ),
        migrations.AlterModelOptions(
            name='consumeritems',
            options={'verbose_name': 'قلم مصرفی', 'verbose_name_plural': 'اقلام مصرفی'},
        ),
        migrations.AlterField(
            model_name='cashassistance',
            name='IdUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.personnel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='consumeritemsregister',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.personnel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='freehelp',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.personnel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='registerloan',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.personnel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='registerorganizationalhouse',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.personnel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='registerproject',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.personnel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='relativesdeathservices',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='seeandvisit',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.personnel', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.personnel', verbose_name='پرسنل'),
        ),
        migrations.CreateModel(
            name='RegisterAssistance',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('DateTimeRegister', models.DateTimeField(auto_now=True, verbose_name='زمان ثبت')),
                ('IdAssistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacilitiesWelfare.assistance', verbose_name='شناسه کمک')),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.personnel', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'ثبت نام کمک',
                'verbose_name_plural': 'ثبت نام کمک ها',
            },
        ),
    ]
