# Generated by Django 3.2.5 on 2021-11-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0037_alter_relativesdeathservices_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalhouse',
            name='DateRegister',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت'),
        ),
    ]
