# Generated by Django 3.2.5 on 2021-12-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0038_alter_organizationalhouse_dateregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freehelp',
            name='Description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
    ]
