# Generated by Django 3.2.5 on 2021-12-03 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0041_alter_freehelp_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freehelp',
            name='DateRegister',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
    ]
