# Generated by Django 3.2.5 on 2021-12-03 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0043_alter_freehelp_dateregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freehelp',
            name='DateRegister',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
