# Generated by Django 3.2.5 on 2021-12-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0044_alter_freehelp_dateregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freehelp',
            name='DateRegister',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
