# Generated by Django 3.2.5 on 2021-12-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcommodity',
            options={'verbose_name': 'گروه', 'verbose_name_plural': 'گروه ها'},
        ),
        migrations.AlterField(
            model_name='commodity',
            name='AddressCommodity',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس کالا'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='BarCodeImage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بارکد'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='BarCodeText',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بارکد'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='MaximumInventory',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر موجودی'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='MinimumInventory',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداقل موجودی'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='OrderAmount',
            field=models.IntegerField(blank=True, null=True, verbose_name='میزان سفارش'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='OrderPoint',
            field=models.IntegerField(blank=True, null=True, verbose_name='نقطه سفارش'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='TechnicalNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره فنی'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='TechnicalSpecifications',
            field=models.TextField(blank=True, null=True, verbose_name='مشخصات فنی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='EconomicNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کدملی/شماره اقتصادی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='FirstBalanceCourse',
            field=models.IntegerField(default=0, verbose_name='مانده اول دوره'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Mobile',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='NationalID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PostalCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='RegistrationNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره ثبت'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='CardNumber',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='Description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='FreightName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام باربری'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='entrycommodity',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='entrycommodity',
            name='Serial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سریال کالا'),
        ),
        migrations.AlterField(
            model_name='productrepaired',
            name='Description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productrepaired',
            name='SerialNumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سریال کالا'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='DateRequired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ نیاز'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseSource',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='منبع خرید'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchasingOfficer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='مامور خرید'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='TechnicalSpecifications',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='مشخصات فنی'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='Taxation',
            field=models.IntegerField(default=0, verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='settlementarrived',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='settlementarrived',
            name='Description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='settlementarrived',
            name='ReceiptNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سند'),
        ),
        migrations.AlterField(
            model_name='storeroom',
            name='Telephone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='transfersbetweenstoreroom',
            name='Description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='FreightNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره بارنامه'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='SourceAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس مبدا'),
        ),
    ]
