# Generated by Django 3.2.5 on 2021-12-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211229_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrepaired',
            name='DateDelivery',
            field=models.DateField(verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='productrepaired',
            name='DateRegistration',
            field=models.DateField(auto_now=True, verbose_name='تاریخ ثبت'),
        ),
    ]
