# Generated by Django 3.2.5 on 2021-12-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20211231_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrepaired',
            name='DateDelivery',
            field=models.DateTimeField(verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='productrepaired',
            name='DateRegistration',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت'),
        ),
    ]
