# Generated by Django 3.2.5 on 2021-10-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_alter_personnel_numberpersonnel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeofstudy',
            options={'verbose_name': 'مقطع تحصیلی', 'verbose_name_plural': 'مقاطع تحصیلی'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': 'پرسنل', 'verbose_name_plural': 'پرسنل ها'},
        ),
        migrations.AlterModelOptions(
            name='profileofchildren',
            options={'verbose_name': 'فرزند', 'verbose_name_plural': 'فرزندان'},
        ),
    ]
