# Generated by Django 3.2.5 on 2021-10-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='NumberPersonnel',
            field=models.IntegerField(unique=True, verbose_name='شماره پرسنلی'),
        ),
    ]
