# Generated by Django 3.2.5 on 2021-11-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_auto_20211011_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='IdCode',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IdGradeofStudy',
            field=models.CharField(choices=[('SI', 'سیکل'), ('DI', 'دیپلم'), ('KA', 'کاردانی'), ('KAR', 'کارشناسی'), ('ARS', 'کارشناسی ارشد'), ('DR', 'دکتری'), ('FDR', 'فوق دکتری'), ('PE', 'پزشک'), ('PEM', 'پزشک متخصص')], default='KAR', max_length=3, verbose_name='مقطع تحصیلی'),
        ),
        migrations.DeleteModel(
            name='GradeofStudy',
        ),
    ]
