# Generated by Django 3.2.5 on 2021-10-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210830_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_FacilitiesWelfare',
            field=models.BooleanField(default=False, verbose_name='مدیر بخش امورات رفاهی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='مدیر نویسنده'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_storekeeper',
            field=models.BooleanField(default=False, verbose_name='مدیر انباردار'),
        ),
    ]
