# Generated by Django 3.2.5 on 2021-12-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0047_auto_20211203_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relativesdeathservices',
            name='Family',
            field=models.CharField(default=1, max_length=50, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
    ]
