# Generated by Django 3.2.5 on 2021-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesWelfare', '0046_auto_20211203_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalhouse',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='organizationalhouse',
            name='Floor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='organizationalhouse',
            name='PostalCode',
            field=models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='کدپستی'),
        ),
        migrations.AlterField(
            model_name='organizationalhouse',
            name='Unit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='relativesdeathservices',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='relativesdeathservices',
            name='Family',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='seeandvisit',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
