# Generated by Django 3.2.5 on 2022-01-08 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20211008_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='IdCity',
        ),
        migrations.AddField(
            model_name='user',
            name='HR_user',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='کاربر منابع انسانی تا'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_HR',
            field=models.BooleanField(default=False, verbose_name='مدیر منابع انسانی'),
        ),
    ]
