# Generated by Django 3.2.5 on 2022-01-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20211008_0059'),
        ('HR', '0004_auto_20211105_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='Address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='DateBirthDay',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='DateMarried',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ازدواج'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='EmergencyNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره اضطراری'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='Gender',
            field=models.CharField(blank=True, choices=[('M', 'مذکر'), ('F', 'مونث')], default='M', max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='HomePhoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره منزل'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IdCity',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.city', verbose_name='نام شهرستان'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IdFieldofStudy',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.fieldofstudy', verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IdGradeofStudy',
            field=models.CharField(blank=True, choices=[('SI', 'سیکل'), ('DI', 'دیپلم'), ('KA', 'کاردانی'), ('KAR', 'کارشناسی'), ('ARS', 'کارشناسی ارشد'), ('DR', 'دکتری'), ('FDR', 'فوق دکتری'), ('PE', 'پزشک'), ('PEM', 'پزشک متخصص')], default='KAR', max_length=3, null=True, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IdGroup',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.group', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IdNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IdPost',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.post', verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='IdProvince',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.province', verbose_name='نام استان'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='MaritalStatus',
            field=models.CharField(blank=True, choices=[('N', 'مجرد'), ('Y', 'متاهل')], default='Y', max_length=1, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='MobileNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
    ]
