# Generated by Django 3.2.5 on 2022-01-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_auto_20220106_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='DateBirthDay',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='DateMarried',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ازدواج'),
        ),
    ]
