# Generated by Django 3.2.5 on 2022-01-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_auto_20220107_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='DateBirthDay',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='DateMarried',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ازدواج'),
        ),
    ]
