# Generated by Django 3.2.5 on 2022-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_auto_20220108_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='Email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='NationalCode',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='UserName',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام کاربری'),
        ),
    ]
