# Generated by Django 3.2.5 on 2022-01-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_auto_20220108_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='IdOrganization',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.organization', verbose_name='سازمان'),
        ),
    ]
